[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS="--version"
[build]
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm run svelte:build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
